name: "Install Build Dependencies"
description: "Install vcpkg libraries and Qt environment for cross-platform builds"

inputs:
  vcpkg_libs:
    description: "vcpkg libraries to install"
    required: false
    default: "breakpad crashpad freeimage giflib opencv[contrib,thread] tl-expected"
    type: string
  qt_modules:
    description: "Qt modules to install"
    required: false
    default: "qt5compat qtnetworkauth qtimageformats"
    type: string
  qt_ver:
    description: "Qt version to install"
    required: false
    default: "6.10.1"
    type: string

runs:
  using: "composite"

  steps:
    - name: Install Custom VCPKG
      uses: RealChuan/install-vcpkg@main

    - name: Delete vcpkg.json
      shell: bash
      run: |
        rm vcpkg.json

    - name: Cache windows vcpkg
      if: runner.os == 'Windows'
      uses: actions/cache@v5
      with:
        path: C:\vcpkg\installed
        key: ${{ runner.os }}-vcpkg-installed-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-installed-
          ${{ runner.os }}-vcpkg-

    - name: Cache macos or linux vcpkg
      if: runner.os == 'macOS' || runner.os == 'Linux'
      uses: actions/cache@v5
      with:
        path: /usr/local/share/vcpkg/installed
        key: ${{ runner.os }}-vcpkg-installed-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-installed-
          ${{ runner.os }}-vcpkg-

    - name: Install dependencies on windows
      if: runner.os == 'Windows'
      shell: bash
      run: |
        ninja --version
        cmake --version
        vcpkg install ${{ inputs.vcpkg_libs }} --triplet x64-windows \
          --clean-buildtrees-after-build --clean-packages-after-build \
          || (cat C:/vcpkg/installed/vcpkg/issue_body.md && exit 1)
        # vcpkg install ${{ inputs.vcpkg_libs }} --triplet x64-windows-static-md \
        #  --clean-buildtrees-after-build --clean-packages-after-build \
        #  || (cat C:/vcpkg/installed/vcpkg/issue_body.md && exit 1)

    - name: Install dependencies on macos
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew install python-setuptools tree
        ninja --version
        cmake --version
        clang --version
        vcpkg install ${{ inputs.vcpkg_libs }} --triplet x64-osx \
          --clean-buildtrees-after-build --clean-packages-after-build \
          || (cat /usr/local/share/vcpkg/installed/vcpkg/issue_body.md && exit 1)
        vcpkg install ${{ inputs.vcpkg_libs }} --triplet arm64-osx \
          --clean-buildtrees-after-build --clean-packages-after-build \
          || (cat /usr/local/share/vcpkg/installed/vcpkg/issue_body.md && exit 1)

    - name: Install dependencies on linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build build-essential libgl1-mesa-dev clang \
          libltdl-dev libxi-dev libxtst-dev libx11-dev libxft-dev libxext-dev libxrandr-dev \
          autoconf autoconf-archive automake libtool
        ninja --version
        cmake --version
        gcc --version
        vcpkg install ${{ inputs.vcpkg_libs }} --triplet x64-linux \
          --clean-buildtrees-after-build --clean-packages-after-build \
          || (cat /usr/local/share/vcpkg/installed/vcpkg/issue_body.md && exit 1)

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{ inputs.qt_ver }}
        modules: ${{ inputs.qt_modules }}
        cache: true
