name: QMake Build

on: 
  push:
    paths-ignore:
        - 'doc/**'
        - '.clang-format'
        - '.gitignore'
        - 'LICENSE'
        - 'README*'
  pull_request:
    paths-ignore: 
        - 'doc/**'
        - '.clang-format'
        - '.gitignore'
        - 'LICENSE'
        - 'README*'

env:
  MACOSX_DEPLOYMENT_TARGET: 11.0

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2019
          - macos-latest
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 1
          
      - uses: ./.github/actions/install-dependencies
        with:
          os_name: ${{ matrix.os }}

      - uses: RealChuan/install-jom@main

      - name: mkdir build
        shell: bash
        run: |
          mkdir build

      - name: msvc-build
        if: startsWith(matrix.os, 'windows')
        shell: pwsh
        run: |
          ..\scripts\windows\setVsDev.ps1 -VersionRange "[16.0,17.0)" -Arch "x64"
          & qmake ./../.
          & jom
        working-directory: build
      - name: ubuntu-build
        if: startsWith(matrix.os, 'ubuntu')
        shell: bash
        run: |
          qmake ./../.
          make -j $(nproc)
        working-directory: build
      - name: macos-build
        if: startsWith(matrix.os, 'macos')
        shell: bash
        run: |
          qmake QMAKE_APPLE_DEVICE_ARCHS="arm64" ./../.
          make -j $(sysctl -n hw.ncpu)
        working-directory: build
        